export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_SUCESS="GET_DATA_SUCESS";
export const GET_DATA_FAILURE="GET_DATA_FAILURE";
export const PAGE_DATA="PAGE_DATA";
export const CORRECT_COUNT="CORRECT_COUNT";
